deploy_production:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'echo -e "Host hopfenspace_sshgateway \n\tUser gateway \n\tHostName hopfenspace.org\n\tCheckHostIP no\nHost pafliefert\n\tHostName 10.0.0.114\n\tUser root\n\tProxyJump hopfenspace_sshgateway" >> ~/.ssh/config'
    - cat ~/.ssh/config
    - echo "$STAGING_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - ssh pafliefert "cd community-isolation-map && git pull && gatsby build && cp -r public live"
  only:
    - master
