deploy_production:
  stage: deploy
  image: tetraweb/php:7.1
  before_script:
    - 'apt-get update -y && apt-get install openssh-client -y'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'echo -e "Host hopfenspace_sshgateway \n\tUser gateway \n\tHostName hopfenspace.org\n\tCheckHostIP no\nHost pafliefert\n\tHostName 10.0.0.114\n\tUser root\n\tProxyJump hopfenspace_sshgateway" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  script:
    - ssh pafliefert "cd community-isolation-map && git pull"
  only:
    - master
